# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate_ST.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalST(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(684, 465)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 240, 381, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 2, 1, 1)
        self.lcdNumber_averagetime = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_averagetime.setObjectName("lcdNumber_averagetime")
        self.gridLayout_2.addWidget(self.lcdNumber_averagetime, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.lcdNumber_normaltime = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_normaltime.setObjectName("lcdNumber_normaltime")
        self.gridLayout_2.addWidget(self.lcdNumber_normaltime, 3, 1, 1, 1)
        self.lcdNumber_standardtime = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_standardtime.setObjectName("lcdNumber_standardtime")
        self.gridLayout_2.addWidget(self.lcdNumber_standardtime, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(150, 10, 381, 221))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.pushButton_calculate = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.gridLayout.addWidget(self.pushButton_calculate, 9, 1, 1, 1)
        self.lineEdit_filerealtime = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_filerealtime.setText("")
        self.lineEdit_filerealtime.setObjectName("lineEdit_filerealtime")
        self.gridLayout.addWidget(self.lineEdit_filerealtime, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.doubleSpinBox_retingfactor = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_retingfactor.setObjectName("doubleSpinBox_retingfactor")
        self.gridLayout.addWidget(self.doubleSpinBox_retingfactor, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.doubleSpinBox_allowances = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_allowances.setObjectName("doubleSpinBox_allowances")
        self.gridLayout.addWidget(self.doubleSpinBox_allowances, 7, 1, 1, 1)
        self.pushButton_browsest = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_browsest.setObjectName("pushButton_browsest")
        self.gridLayout.addWidget(self.pushButton_browsest, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "calculate_standard_time"))
        self.label_4.setText(_translate("Form", "s"))
        self.label_5.setText(_translate("Form", "Average Time:"))
        self.label_3.setText(_translate("Form", "Time:Itme/s"))
        self.label_8.setText(_translate("Form", "Normal Time:"))
        self.label_9.setText(_translate("Form", "Standard Time"))
        self.label_10.setText(_translate("Form", "s"))
        self.label_11.setText(_translate("Form", "s"))
        self.label_7.setText(_translate("Form", "Allowances(%)"))
        self.pushButton_calculate.setText(_translate("Form", "Calculate"))
        self.label_6.setText(_translate("Form", "Reting Factor(%)"))
        self.label.setText(_translate("Form", "select file:"))
        self.label_2.setText(_translate("Form", "real_Right_<name>_<lastname>_<index>.csv"))
        self.pushButton_browsest.setText(_translate("Form", "Browse..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_CalST()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
